### ISSUE TITLE
Documentation on npmjs.com incorrect

### ISSUE THREAD

**Issue by e2jk** [AndreasPizsa/md5-jkmyers#1]
On https://www.npmjs.com/package/md5-jkmyers the documentation for Node.js indicates

```
md5 = require('md5')
md5('hello, world!')
```

However I've had to do `md5 = require('md5-jkmyers');` for it to work.
Could you update the documentation?
(note: I use `npm` to create a clienside-application using [Ampersand.js](http://ampersandjs.com/), not sure if using Node for the server would be any different)

**Comment by andreaspitzer** [comment]
Hey @e2jk,
thanks for this report and correction. This somehow slipped through my e-mails, so I'm seeing it only just now - my apologies. The good news: @cylwin provided a fix that I just merged.

Thanks!

Best,
Andreas
